[package]
name = "mws2vddgpupt"
description = "Move workspaces to visible display during GPU passthrough."
version = "0.2.0"
authors = ["lae"]
edition = "2018"

[dependencies]
i3ipc = "0.10.1"
exec = "0.3.1"
quickrandr = "0.3.2"
virt = "0.2.10"
clap = "2.33.0"
indicatif = "0.11.0"
